apiVersion: v1
kind: Secret
metadata:
  name: ella-token
  labels:
    getkloak.io/enabled: "true"
    getkloak.io/hosts: "core.ella.gbourgeois.com"
data:
  token: ZWxsYWNvcmVfMlRGdWdPUHlFTjV6X250RXZpNnowMFB5NWFLRUFYMU8yMko4dQo=


