apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rust-rustls
  labels:
    app: demo-rust-rustls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rust-rustls
  template:
    metadata:
      labels:
        app: demo-rust-rustls
      annotations:
        getkloak.io/enabled: "true"
    spec:
      containers:
        - name: demo-rust-rustls
          image: kloak-demo-rust-rustls:latest
          imagePullPolicy: Never
          env:
            - name: TARGET_URL
              value: "https://httpbin.org/headers"
            - name: REQUEST_INTERVAL
              value: "5"
            - name: SECRET_ALLOWED_FILE
              value: "/etc/secrets/allowed/secret"
            - name: SECRET_BLOCKED_FILE
              value: "/etc/secrets/blocked/secret"
          volumeMounts:
            - name: secret-allowed
              mountPath: /etc/secrets/allowed
              readOnly: true
            - name: secret-blocked
              mountPath: /etc/secrets/blocked
              readOnly: true
      volumes:
        - name: secret-allowed
          secret:
            secretName: demo-secret-allowed
        - name: secret-blocked
          secret:
            secretName: demo-secret-blocked
