// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: pkg/sync/sync.proto

package sync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_WatchSecrets_FullMethodName = "/kloak.sync.v1.SyncService/WatchSecrets"
	SyncService_GetSecrets_FullMethodName   = "/kloak.sync.v1.SyncService/GetSecrets"
	SyncService_StoreHash_FullMethodName    = "/kloak.sync.v1.SyncService/StoreHash"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncService provides secret synchronization between controller and agents.
type SyncServiceClient interface {
	// WatchSecrets streams secret updates from controller to agents.
	// Agents subscribe with optional namespace filter and receive all matching secrets.
	WatchSecrets(ctx context.Context, in *WatchSecretsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SecretEvent], error)
	// GetSecrets fetches current secrets (pull model, for initial sync).
	GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error)
	// StoreHash stores a hash→value mapping (called by webhook).
	StoreHash(ctx context.Context, in *StoreHashRequest, opts ...grpc.CallOption) (*StoreHashResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) WatchSecrets(ctx context.Context, in *WatchSecretsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SecretEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], SyncService_WatchSecrets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSecretsRequest, SecretEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_WatchSecretsClient = grpc.ServerStreamingClient[SecretEvent]

func (c *syncServiceClient) GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretsResponse)
	err := c.cc.Invoke(ctx, SyncService_GetSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) StoreHash(ctx context.Context, in *StoreHashRequest, opts ...grpc.CallOption) (*StoreHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreHashResponse)
	err := c.cc.Invoke(ctx, SyncService_StoreHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// SyncService provides secret synchronization between controller and agents.
type SyncServiceServer interface {
	// WatchSecrets streams secret updates from controller to agents.
	// Agents subscribe with optional namespace filter and receive all matching secrets.
	WatchSecrets(*WatchSecretsRequest, grpc.ServerStreamingServer[SecretEvent]) error
	// GetSecrets fetches current secrets (pull model, for initial sync).
	GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error)
	// StoreHash stores a hash→value mapping (called by webhook).
	StoreHash(context.Context, *StoreHashRequest) (*StoreHashResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) WatchSecrets(*WatchSecretsRequest, grpc.ServerStreamingServer[SecretEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchSecrets not implemented")
}
func (UnimplementedSyncServiceServer) GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecrets not implemented")
}
func (UnimplementedSyncServiceServer) StoreHash(context.Context, *StoreHashRequest) (*StoreHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreHash not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_WatchSecrets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSecretsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncServiceServer).WatchSecrets(m, &grpc.GenericServerStream[WatchSecretsRequest, SecretEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_WatchSecretsServer = grpc.ServerStreamingServer[SecretEvent]

func _SyncService_GetSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_GetSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetSecrets(ctx, req.(*GetSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_StoreHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).StoreHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_StoreHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).StoreHash(ctx, req.(*StoreHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kloak.sync.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecrets",
			Handler:    _SyncService_GetSecrets_Handler,
		},
		{
			MethodName: "StoreHash",
			Handler:    _SyncService_StoreHash_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSecrets",
			Handler:       _SyncService_WatchSecrets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/sync/sync.proto",
}
