// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: pkg/sync/sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_ADD         EventType = 1
	EventType_EVENT_TYPE_UPDATE      EventType = 2
	EventType_EVENT_TYPE_DELETE      EventType = 3
	// Full sync - agent should replace all secrets.
	EventType_EVENT_TYPE_SYNC EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_ADD",
		2: "EVENT_TYPE_UPDATE",
		3: "EVENT_TYPE_DELETE",
		4: "EVENT_TYPE_SYNC",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_ADD":         1,
		"EVENT_TYPE_UPDATE":      2,
		"EVENT_TYPE_DELETE":      3,
		"EVENT_TYPE_SYNC":        4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_sync_sync_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_sync_sync_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{0}
}

// WatchSecretsRequest configures the watch stream.
type WatchSecretsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: only receive secrets for these namespaces.
	// Empty means all namespaces.
	Namespaces []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Optional: node name for filtering (future use).
	NodeName      string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSecretsRequest) Reset() {
	*x = WatchSecretsRequest{}
	mi := &file_pkg_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSecretsRequest) ProtoMessage() {}

func (x *WatchSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSecretsRequest.ProtoReflect.Descriptor instead.
func (*WatchSecretsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *WatchSecretsRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *WatchSecretsRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

// SecretEvent represents a change to a secret.
type SecretEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of event.
	Type EventType `protobuf:"varint,1,opt,name=type,proto3,enum=kloak.sync.v1.EventType" json:"type,omitempty"`
	// The hash (kloak:xxx format).
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// The secret value (only for ADD/UPDATE).
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Allowed hosts for this secret.
	AllowedHosts []string `protobuf:"bytes,4,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	// Namespace the secret belongs to.
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pod ID that owns this secret (if applicable).
	PodId         string `protobuf:"bytes,6,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretEvent) Reset() {
	*x = SecretEvent{}
	mi := &file_pkg_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretEvent) ProtoMessage() {}

func (x *SecretEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretEvent.ProtoReflect.Descriptor instead.
func (*SecretEvent) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SecretEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *SecretEvent) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SecretEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretEvent) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *SecretEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SecretEvent) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

// GetSecretsRequest requests current secrets.
type GetSecretsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional namespace filter.
	Namespaces    []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_pkg_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretsRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// GetSecretsResponse contains all current secrets.
type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretEntry         `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_pkg_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretsResponse) GetSecrets() []*SecretEntry {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// SecretEntry represents a stored secret.
type SecretEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AllowedHosts  []string               `protobuf:"bytes,3,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodId         string                 `protobuf:"bytes,5,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretEntry) Reset() {
	*x = SecretEntry{}
	mi := &file_pkg_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretEntry) ProtoMessage() {}

func (x *SecretEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretEntry.ProtoReflect.Descriptor instead.
func (*SecretEntry) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SecretEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SecretEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretEntry) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *SecretEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SecretEntry) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

// StoreHashRequest stores a new hash→value mapping.
// Called by webhook when it hashes environment variables.
type StoreHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AllowedHosts  []string               `protobuf:"bytes,3,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	PodId         string                 `protobuf:"bytes,4,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHashRequest) Reset() {
	*x = StoreHashRequest{}
	mi := &file_pkg_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHashRequest) ProtoMessage() {}

func (x *StoreHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHashRequest.ProtoReflect.Descriptor instead.
func (*StoreHashRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *StoreHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *StoreHashRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StoreHashRequest) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *StoreHashRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *StoreHashRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// StoreHashResponse confirms storage.
type StoreHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHashResponse) Reset() {
	*x = StoreHashResponse{}
	mi := &file_pkg_sync_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHashResponse) ProtoMessage() {}

func (x *StoreHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sync_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHashResponse.ProtoReflect.Descriptor instead.
func (*StoreHashResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sync_sync_proto_rawDescGZIP(), []int{6}
}

func (x *StoreHashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreHashResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_sync_sync_proto protoreflect.FileDescriptor

const file_pkg_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/sync/sync.proto\x12\rkloak.sync.v1\"R\n" +
	"\x13WatchSecretsRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"\xbf\x01\n" +
	"\vSecretEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.kloak.sync.v1.EventTypeR\x04type\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12#\n" +
	"\rallowed_hosts\x18\x04 \x03(\tR\fallowedHosts\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x15\n" +
	"\x06pod_id\x18\x06 \x01(\tR\x05podId\"3\n" +
	"\x11GetSecretsRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\"J\n" +
	"\x12GetSecretsResponse\x124\n" +
	"\asecrets\x18\x01 \x03(\v2\x1a.kloak.sync.v1.SecretEntryR\asecrets\"\x91\x01\n" +
	"\vSecretEntry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12#\n" +
	"\rallowed_hosts\x18\x03 \x03(\tR\fallowedHosts\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x15\n" +
	"\x06pod_id\x18\x05 \x01(\tR\x05podId\"\x96\x01\n" +
	"\x10StoreHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12#\n" +
	"\rallowed_hosts\x18\x03 \x03(\tR\fallowedHosts\x12\x15\n" +
	"\x06pod_id\x18\x04 \x01(\tR\x05podId\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\"C\n" +
	"\x11StoreHashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*~\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_ADD\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_UPDATE\x10\x02\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x03\x12\x13\n" +
	"\x0fEVENT_TYPE_SYNC\x10\x042\x82\x02\n" +
	"\vSyncService\x12P\n" +
	"\fWatchSecrets\x12\".kloak.sync.v1.WatchSecretsRequest\x1a\x1a.kloak.sync.v1.SecretEvent0\x01\x12Q\n" +
	"\n" +
	"GetSecrets\x12 .kloak.sync.v1.GetSecretsRequest\x1a!.kloak.sync.v1.GetSecretsResponse\x12N\n" +
	"\tStoreHash\x12\x1f.kloak.sync.v1.StoreHashRequest\x1a .kloak.sync.v1.StoreHashResponseB+Z)github.com/spinningfactory/kloak/pkg/syncb\x06proto3"

var (
	file_pkg_sync_sync_proto_rawDescOnce sync.Once
	file_pkg_sync_sync_proto_rawDescData []byte
)

func file_pkg_sync_sync_proto_rawDescGZIP() []byte {
	file_pkg_sync_sync_proto_rawDescOnce.Do(func() {
		file_pkg_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_sync_sync_proto_rawDesc), len(file_pkg_sync_sync_proto_rawDesc)))
	})
	return file_pkg_sync_sync_proto_rawDescData
}

var file_pkg_sync_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_sync_sync_proto_goTypes = []any{
	(EventType)(0),              // 0: kloak.sync.v1.EventType
	(*WatchSecretsRequest)(nil), // 1: kloak.sync.v1.WatchSecretsRequest
	(*SecretEvent)(nil),         // 2: kloak.sync.v1.SecretEvent
	(*GetSecretsRequest)(nil),   // 3: kloak.sync.v1.GetSecretsRequest
	(*GetSecretsResponse)(nil),  // 4: kloak.sync.v1.GetSecretsResponse
	(*SecretEntry)(nil),         // 5: kloak.sync.v1.SecretEntry
	(*StoreHashRequest)(nil),    // 6: kloak.sync.v1.StoreHashRequest
	(*StoreHashResponse)(nil),   // 7: kloak.sync.v1.StoreHashResponse
}
var file_pkg_sync_sync_proto_depIdxs = []int32{
	0, // 0: kloak.sync.v1.SecretEvent.type:type_name -> kloak.sync.v1.EventType
	5, // 1: kloak.sync.v1.GetSecretsResponse.secrets:type_name -> kloak.sync.v1.SecretEntry
	1, // 2: kloak.sync.v1.SyncService.WatchSecrets:input_type -> kloak.sync.v1.WatchSecretsRequest
	3, // 3: kloak.sync.v1.SyncService.GetSecrets:input_type -> kloak.sync.v1.GetSecretsRequest
	6, // 4: kloak.sync.v1.SyncService.StoreHash:input_type -> kloak.sync.v1.StoreHashRequest
	2, // 5: kloak.sync.v1.SyncService.WatchSecrets:output_type -> kloak.sync.v1.SecretEvent
	4, // 6: kloak.sync.v1.SyncService.GetSecrets:output_type -> kloak.sync.v1.GetSecretsResponse
	7, // 7: kloak.sync.v1.SyncService.StoreHash:output_type -> kloak.sync.v1.StoreHashResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_sync_sync_proto_init() }
func file_pkg_sync_sync_proto_init() {
	if File_pkg_sync_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sync_sync_proto_rawDesc), len(file_pkg_sync_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_sync_sync_proto_goTypes,
		DependencyIndexes: file_pkg_sync_sync_proto_depIdxs,
		EnumInfos:         file_pkg_sync_sync_proto_enumTypes,
		MessageInfos:      file_pkg_sync_sync_proto_msgTypes,
	}.Build()
	File_pkg_sync_sync_proto = out.File
	file_pkg_sync_sync_proto_goTypes = nil
	file_pkg_sync_sync_proto_depIdxs = nil
}
