apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-boringssl
  labels:
    app: demo-boringssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-boringssl
  template:
    metadata:
      labels:
        app: demo-boringssl
      annotations:
        getkloak.io/enabled: "true"
    spec:
      containers:
        - name: demo-app
          image: kloak-demo-boringssl:latest
          imagePullPolicy: Never
          env:
            - name: SECRET_ALLOWED_FILE
              value: "/etc/secrets/allowed/api-key"
            - name: SECRET_BLOCKED_FILE
              value: "/etc/secrets/blocked/api-key"
            - name: TARGET_HOST
              value: "httpbin.org"
            - name: REQUEST_INTERVAL
              value: "5"
          volumeMounts:
            - name: secret-allowed-vol
              mountPath: "/etc/secrets/allowed"
              readOnly: true
            - name: secret-blocked-vol
              mountPath: "/etc/secrets/blocked"
              readOnly: true
      volumes:
        - name: secret-allowed-vol
          secret:
            secretName: secret-allowed
        - name: secret-blocked-vol
          secret:
            secretName: secret-blocked
