apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
  namespace: kloak-local
  labels:
    app: demo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
      annotations:
        getkloak.io/enabled: "true"
    spec:
      containers:
        - name: demo-app
          image: kloak-demo-go:latest
          imagePullPolicy: Never
          env:
            - name: SECRET_ALLOWED_FILE
              value: "/etc/secrets/allowed/api-key"
            - name: SECRET_BLOCKED_FILE
              value: "/etc/secrets/blocked/api-key"
            - name: TARGET_URL
              value: "https://httpbin.org/headers"
            - name: REQUEST_INTERVAL
              value: "5"
          volumeMounts:
            - name: secret-allowed-vol
              mountPath: "/etc/secrets/allowed"
              readOnly: true
            - name: secret-blocked-vol
              mountPath: "/etc/secrets/blocked"
              readOnly: true
      volumes:
        - name: secret-allowed-vol
          secret:
            secretName: secret-api-key
        - name: secret-blocked-vol
          secret:
            secretName: secret-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python
  namespace: kloak-local
  labels:
    app: demo-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-python
  template:
    metadata:
      labels:
        app: demo-python
      annotations:
        getkloak.io/enabled: "true"
    spec:
      containers:
        - name: demo-app
          image: kloak-demo-python:latest
          imagePullPolicy: Never
          env:
            - name: SECRET_ALLOWED_FILE
              value: "/etc/secrets/allowed/api-key"
            - name: SECRET_BLOCKED_FILE
              value: "/etc/secrets/blocked/api-key"
            - name: TARGET_URL
              value: "https://httpbin.org/headers"
            - name: REQUEST_INTERVAL
              value: "5"
          volumeMounts:
            - name: secret-allowed-vol
              mountPath: "/etc/secrets/allowed"
              readOnly: true
            - name: secret-blocked-vol
              mountPath: "/etc/secrets/blocked"
              readOnly: true
      volumes:
        - name: secret-allowed-vol
          secret:
            secretName: secret-db-password
        - name: secret-blocked-vol
          secret:
            secretName: secret-api-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rust-openssl
  namespace: kloak-local
  labels:
    app: demo-rust-openssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rust-openssl
  template:
    metadata:
      labels:
        app: demo-rust-openssl
      annotations:
        getkloak.io/enabled: "true"
    spec:
      containers:
        - name: demo-app
          image: kloak-demo-rust-openssl:latest
          imagePullPolicy: Never
          env:
            - name: SECRET_ALLOWED_FILE
              value: "/etc/secrets/allowed/api-key"
            - name: SECRET_BLOCKED_FILE
              value: "/etc/secrets/blocked/api-key"
            - name: TARGET_URL
              value: "https://httpbin.org/headers"
            - name: REQUEST_INTERVAL
              value: "5"
            - name: INITIAL_WAIT
              value: "15"
          volumeMounts:
            - name: secret-allowed-vol
              mountPath: "/etc/secrets/allowed"
              readOnly: true
            - name: secret-blocked-vol
              mountPath: "/etc/secrets/blocked"
              readOnly: true
      volumes:
        - name: secret-allowed-vol
          secret:
            secretName: secret-webhook
        - name: secret-blocked-vol
          secret:
            secretName: secret-db-password
