apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests

images:
  - name: kloak
    newName: kloak
    newTag: latest
  - name: bitnami/kubectl
    newName: bitnami/kubectl
    newTag: latest
