apiVersion: v1
kind: Service
metadata:
  name: tls
  labels:
    app: tls
spec:
  selector:
    app: demo-python-sni
  ports:
    - port: 8443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-sni
  labels:
    app: demo-python-sni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-python-sni
  template:
    metadata:
      labels:
        app: demo-python-sni
      annotations:
        getkloak.io/enabled: "true"
    spec:
      containers:
        - name: demo-app
          image: kloak-demo-python-sni:latest
          imagePullPolicy: Never
          command: ["python", "-u", "app.py"]
          env:
            - name: SECRET_ALLOWED_FILE
              value: "/etc/secrets/allowed/api-key"
            - name: SECRET_BLOCKED_FILE
              value: "/etc/secrets/blocked/api-key"
            - name: TARGET_HOST
              value: "tls"
            - name: REQUEST_INTERVAL
              value: "5"
          volumeMounts:
            - name: secret-allowed-vol
              mountPath: "/etc/secrets/allowed"
              readOnly: true
            - name: secret-blocked-vol
              mountPath: "/etc/secrets/blocked"
              readOnly: true
        - name: echo-server
          image: kloak-demo-python-sni:latest
          imagePullPolicy: Never
          command: ["python", "-u", "echo_server.py"]
          ports:
            - containerPort: 8443
      volumes:
        - name: secret-allowed-vol
          secret:
            secretName: secret-allowed
        - name: secret-blocked-vol
          secret:
            secretName: secret-blocked
