apiVersion: v1
kind: Service
metadata:
  name: kloak-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  clusterIP: None
  ports:
    - name: http-store
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: grpc-sync
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "kloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
