{{- if .Values.demo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kloak.fullname" . }}-demo-allowed
  namespace: {{ .Values.demo.namespace }}
  labels:
    {{- include "kloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo
    getkloak.io/enabled: "true"
  annotations:
    getkloak.io/hosts: {{ .Values.demo.secretAllowed.allowedHost | quote }}
type: Opaque
data:
  api-key: {{ .Values.demo.secretAllowed.value | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kloak.fullname" . }}-demo-blocked
  namespace: {{ .Values.demo.namespace }}
  labels:
    {{- include "kloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo
    getkloak.io/enabled: "true"
  annotations:
    getkloak.io/hosts: {{ .Values.demo.secretBlocked.allowedHost | quote }}
type: Opaque
data:
  api-key: {{ .Values.demo.secretBlocked.value | b64enc | quote }}
{{- end }}
