{{- if .Values.demo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kloak.fullname" . }}-demo-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo
    getkloak.io/enabled: "true"
  {{- if .Values.demo.secret.allowedHost }}
  annotations:
    getkloak.io/hosts: {{ .Values.demo.secret.allowedHost | quote }}
  {{- end }}
type: Opaque
data:
  api-key: {{ .Values.demo.secret.value | b64enc | quote }}
{{- end }}
