apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kloak-mutating-webhook
  labels:
    {{- include "kloak.labels" . | nindent 4 }}
  {{- if eq .Values.certificates.mode "certManager" }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kloak-webhook-cert
  {{- end }}
webhooks:
  - name: pod.mutate.getkloak.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: kloak-webhook
        path: /mutate-pods
      {{- if eq .Values.certificates.mode "auto" }}
      # caBundle is patched automatically by the cert-gen job
      {{- end }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: getkloak.io/enabled
          operator: In
          values: ["true"]
    failurePolicy: Fail
