apiVersion: v1
kind: Service
metadata:
  name: kloak-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "kloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
