// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/cni/api/cni.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_ADD   Command = 0
	Command_DEL   Command = 1
	Command_CHECK Command = 2
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "ADD",
		1: "DEL",
		2: "CHECK",
	}
	Command_value = map[string]int32{
		"ADD":   0,
		"DEL":   1,
		"CHECK": 2,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cni_api_cni_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_pkg_cni_api_cni_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cni_api_cni_proto_rawDescGZIP(), []int{0}
}

type PodRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Command     Command                `protobuf:"varint,1,opt,name=command,proto3,enum=cni.api.Command" json:"command,omitempty"`
	ContainerId string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Netns       string                 `protobuf:"bytes,3,opt,name=netns,proto3" json:"netns,omitempty"`
	Ifname      string                 `protobuf:"bytes,4,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Args        string                 `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Path        string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	StdinData   []byte                 `protobuf:"bytes,7,opt,name=stdin_data,json=stdinData,proto3" json:"stdin_data,omitempty"`
	// Metadata extracted from env/args
	PodName       string `protobuf:"bytes,8,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string `protobuf:"bytes,9,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodUid        string `protobuf:"bytes,10,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRequest) Reset() {
	*x = PodRequest{}
	mi := &file_pkg_cni_api_cni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRequest) ProtoMessage() {}

func (x *PodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_api_cni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRequest.ProtoReflect.Descriptor instead.
func (*PodRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cni_api_cni_proto_rawDescGZIP(), []int{0}
}

func (x *PodRequest) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_ADD
}

func (x *PodRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PodRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *PodRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *PodRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *PodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PodRequest) GetStdinData() []byte {
	if x != nil {
		return x.StdinData
	}
	return nil
}

func (x *PodRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PodRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

type PodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodResponse) Reset() {
	*x = PodResponse{}
	mi := &file_pkg_cni_api_cni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodResponse) ProtoMessage() {}

func (x *PodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_api_cni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodResponse.ProtoReflect.Descriptor instead.
func (*PodResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cni_api_cni_proto_rawDescGZIP(), []int{1}
}

var File_pkg_cni_api_cni_proto protoreflect.FileDescriptor

const file_pkg_cni_api_cni_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/cni/api/cni.proto\x12\acni.api\"\xa9\x02\n" +
	"\n" +
	"PodRequest\x12*\n" +
	"\acommand\x18\x01 \x01(\x0e2\x10.cni.api.CommandR\acommand\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05netns\x18\x03 \x01(\tR\x05netns\x12\x16\n" +
	"\x06ifname\x18\x04 \x01(\tR\x06ifname\x12\x12\n" +
	"\x04args\x18\x05 \x01(\tR\x04args\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"stdin_data\x18\a \x01(\fR\tstdinData\x12\x19\n" +
	"\bpod_name\x18\b \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\t \x01(\tR\fpodNamespace\x12\x17\n" +
	"\apod_uid\x18\n" +
	" \x01(\tR\x06podUid\"\r\n" +
	"\vPodResponse*&\n" +
	"\aCommand\x12\a\n" +
	"\x03ADD\x10\x00\x12\a\n" +
	"\x03DEL\x10\x01\x12\t\n" +
	"\x05CHECK\x10\x022?\n" +
	"\x03CNI\x128\n" +
	"\tHandlePod\x12\x13.cni.api.PodRequest\x1a\x14.cni.api.PodResponse\"\x00B.Z,github.com/spinningfactory/kloak/pkg/cni/apib\x06proto3"

var (
	file_pkg_cni_api_cni_proto_rawDescOnce sync.Once
	file_pkg_cni_api_cni_proto_rawDescData []byte
)

func file_pkg_cni_api_cni_proto_rawDescGZIP() []byte {
	file_pkg_cni_api_cni_proto_rawDescOnce.Do(func() {
		file_pkg_cni_api_cni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cni_api_cni_proto_rawDesc), len(file_pkg_cni_api_cni_proto_rawDesc)))
	})
	return file_pkg_cni_api_cni_proto_rawDescData
}

var file_pkg_cni_api_cni_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cni_api_cni_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_cni_api_cni_proto_goTypes = []any{
	(Command)(0),        // 0: cni.api.Command
	(*PodRequest)(nil),  // 1: cni.api.PodRequest
	(*PodResponse)(nil), // 2: cni.api.PodResponse
}
var file_pkg_cni_api_cni_proto_depIdxs = []int32{
	0, // 0: cni.api.PodRequest.command:type_name -> cni.api.Command
	1, // 1: cni.api.CNI.HandlePod:input_type -> cni.api.PodRequest
	2, // 2: cni.api.CNI.HandlePod:output_type -> cni.api.PodResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_cni_api_cni_proto_init() }
func file_pkg_cni_api_cni_proto_init() {
	if File_pkg_cni_api_cni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cni_api_cni_proto_rawDesc), len(file_pkg_cni_api_cni_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cni_api_cni_proto_goTypes,
		DependencyIndexes: file_pkg_cni_api_cni_proto_depIdxs,
		EnumInfos:         file_pkg_cni_api_cni_proto_enumTypes,
		MessageInfos:      file_pkg_cni_api_cni_proto_msgTypes,
	}.Build()
	File_pkg_cni_api_cni_proto = out.File
	file_pkg_cni_api_cni_proto_goTypes = nil
	file_pkg_cni_api_cni_proto_depIdxs = nil
}
