package ebpf

import (
	"debug/elf"
	"encoding/binary"
	"fmt"
	"path/filepath"
	"strings"
)

// ChainType constants for TLS library H extraction paths.
const (
	ChainOpenSSL4Hop = 0 // OpenSSL 3.2+: SSL→wrl→enc_ctx→algctx→H (4 pointer derefs)
	ChainBoringSSL   = 1 // BoringSSL:    SSL→s3→aead_write_ctx→H  (2 derefs + direct read)
)

// TLSOffsets contains struct offsets for extracting TLS key material from an
// SSL* object at runtime. The ChainType field selects which pointer chain
// the BPF program follows:
//
//	OpenSSL 3.2+ (ChainType=0):
//	  SSL* + SSLToWRL → wrl* + WRLToEncCtx → enc_ctx* + EncCtxToAlgctx → algctx* + AlgctxToH → H
//
//	BoringSSL (ChainType=1):
//	  SSL* + SSLToS3 → s3* + S3ToAEAD → aead_ctx* + AEADToH → H
//
// These are version-specific and must match the TLS library build in the container.
// The struct layout must match struct tls_offsets in tls_uprobe.c exactly.
type TLSOffsets struct {
	ChainType uint32 // 0=OpenSSL 4-hop, 1=BoringSSL

	// OpenSSL 3.2+ (4-hop chain)
	SSLToWRL       uint32 // SSL* + off → OSSL_RECORD_LAYER* (pointer deref)
	WRLToEncCtx    uint32 // wrl* + off → EVP_CIPHER_CTX* (pointer deref)
	EncCtxToAlgctx uint32 // enc_ctx* + off → algctx/PROV_GCM_CTX* (pointer deref)
	AlgctxToH      uint32 // algctx* + off → H (16 bytes, direct read)

	// BoringSSL (2-deref chain)
	SSLToS3  uint32 // SSL* + off → SSL3_STATE* (pointer deref)
	S3ToAEAD uint32 // s3* + off → SSLAEADContext* (pointer deref, UniquePtr)
	AEADToH  uint32 // aead_ctx* + off → H (16 bytes, direct read)

	// Shared: configurable BIO offsets for ssl_read_fd.
	// 0 means use the default (88 for wbio, 56 for bio_num).
	WBIOOffset   uint32 // SSL* + off → BIO* (pointer deref)
	BIONumOffset uint32 // BIO* + off → fd (int read)
}

// tlsOffsetTable maps TLS library version strings to their struct offsets.
// Keys are "X.Y" for OpenSSL or "boringssl" for BoringSSL.
// Offsets determined by building with debug symbols and inspecting with pahole.
var tlsOffsetTable = map[string]TLSOffsets{
	// ── OpenSSL 3.2+ (4-hop chain) ──
	// Offsets verified via pahole on both aarch64 and x86_64 (identical).
	// Generated by tools/openssl-offsets/discover.sh.
	// Chain: SSL_CONNECTION.rlayer.wrl → enc_ctx → algctx → gcm.H

	// OpenSSL 3.5.x — SSLToWRL grew due to new fields in SSL_CONNECTION.
	"3.5": {ChainType: ChainOpenSSL4Hop, SSLToWRL: 3208, WRLToEncCtx: 4128, EncCtxToAlgctx: 176, AlgctxToH: 328},

	// OpenSSL 3.2.x–3.4.x — identical offsets across these versions.
	"3.4": {ChainType: ChainOpenSSL4Hop, SSLToWRL: 3056, WRLToEncCtx: 4128, EncCtxToAlgctx: 168, AlgctxToH: 328},
	"3.3": {ChainType: ChainOpenSSL4Hop, SSLToWRL: 3056, WRLToEncCtx: 4128, EncCtxToAlgctx: 168, AlgctxToH: 328},
	"3.2": {ChainType: ChainOpenSSL4Hop, SSLToWRL: 3056, WRLToEncCtx: 4128, EncCtxToAlgctx: 168, AlgctxToH: 328},

	// OpenSSL 3.0.x–3.1.x — 3-hop chain (no record layer indirection).
	// TODO: Implement 3-hop chain support in BPF.
	// "3.1": {...},
	// "3.0": {...},

	// ── BoringSSL ──
	// Offsets verified via pahole on aarch64 (tools/boringssl-offsets/).
	// Chain: ssl_st.s3 → SSL3_STATE.aead_write_ctx → SSLAEADContext+16 → H
	// BoringSSL has no stable version numbers; offsets are for the version
	// bundled with Go 1.25 (GOEXPERIMENT=boringcrypto) and standalone HEAD.
	"boringssl": {
		ChainType:    ChainBoringSSL,
		SSLToS3:      48,  // ssl_st.s3 (SSL3_STATE*)
		S3ToAEAD:     272, // SSL3_STATE.aead_write_ctx (UniquePtr<SSLAEADContext>)
		AEADToH:      16,  // SSLAEADContext: 8 (ctx_) + 8 (EVP_AEAD_CTX.state) → Htable[0]
		WBIOOffset:   32,  // ssl_st.wbio (vs OpenSSL's 88)
		BIONumOffset: 56,  // bio_st.num (same as OpenSSL)
	},
}

// DetectTLSLibrary reads a TLS shared library or statically-linked binary from
// a container's filesystem and determines its type (OpenSSL or BoringSSL) and
// version. Returns the version string and corresponding struct offsets.
func DetectTLSLibrary(pid int, libPath string) (version string, offsets TLSOffsets, err error) {
	return detectTLSLibraryFromPath(fmt.Sprintf("/proc/%d/root%s", pid, libPath))
}

// detectTLSLibraryFromHostPath detects the TLS library from a host-accessible path
// (e.g., /proc/<pid>/exe for statically linked binaries).
func detectTLSLibraryFromHostPath(hostPath string) (string, TLSOffsets, error) {
	return detectTLSLibraryFromPath(hostPath)
}

func detectTLSLibraryFromPath(hostPath string) (version string, offsets TLSOffsets, err error) {
	f, err := elf.Open(hostPath)
	if err != nil {
		return "", TLSOffsets{}, fmt.Errorf("opening ELF %s: %w", hostPath, err)
	}
	defer func() { _ = f.Close() }()

	// Check for BoringSSL first (must come before OpenSSL since BoringSSL
	// also contains "OpenSSL" strings for compatibility).
	if isBoringSSL(f) {
		offsets, ok := tlsOffsetTable["boringssl"]
		if !ok {
			return "boringssl", TLSOffsets{}, fmt.Errorf("BoringSSL offsets not in table")
		}
		return "boringssl", offsets, nil
	}

	version, err = readOpenSSLVersion(f)
	if err != nil {
		// If this is a libssl.so with neither "BoringSSL" nor "OpenSSL" strings,
		// the version string may live in the sibling libcrypto.so (BoringSSL puts
		// "BoringSSL" in libcrypto, not libssl). Check the sibling before giving up.
		if isLibSSL(hostPath) {
			if borVer, borOff, borErr := checkSiblingCryptoForBoringSSL(hostPath); borErr == nil {
				return borVer, borOff, nil
			}
		}
		return "", TLSOffsets{}, fmt.Errorf("reading TLS library version from %s: %w", hostPath, err)
	}

	majorMinor := extractMajorMinor(version)
	offsets, ok := tlsOffsetTable[majorMinor]
	if !ok {
		return version, TLSOffsets{}, fmt.Errorf("unsupported OpenSSL version %s (major.minor=%s)", version, majorMinor)
	}

	if offsets.SSLToWRL == 0 && offsets.ChainType == ChainOpenSSL4Hop {
		return version, offsets, fmt.Errorf("OpenSSL %s offsets not yet calibrated (SSLToWRL=0)", version)
	}

	return version, offsets, nil
}

// DetectOpenSSLVersion is an alias for DetectTLSLibrary for backwards compatibility.
func DetectOpenSSLVersion(pid int, libPath string) (string, TLSOffsets, error) {
	return DetectTLSLibrary(pid, libPath)
}

// isBoringSSL checks if an ELF file is a BoringSSL library by searching for
// BoringSSL-specific strings or symbols.
func isBoringSSL(f *elf.File) bool {
	for _, name := range []string{".rodata", ".data"} {
		sec := f.Section(name)
		if sec == nil {
			continue
		}
		data, err := sec.Data()
		if err != nil {
			continue
		}
		if containsBytes(data, []byte("BoringSSL")) {
			return true
		}
	}
	// Check dynamic symbols for BoringSSL-specific exports.
	syms, err := f.DynamicSymbols()
	if err == nil {
		for _, sym := range syms {
			if strings.HasPrefix(sym.Name, "BORINGSSL_") {
				return true
			}
		}
	}
	// Check regular symbols (for statically linked Go+BoringCrypto).
	syms, err = f.Symbols()
	if err == nil {
		for _, sym := range syms {
			if strings.Contains(sym.Name, "BORINGSSL") || strings.Contains(sym.Name, "boringssl") {
				return true
			}
		}
	}
	return false
}

// isLibSSL returns true if the path looks like a libssl shared library.
func isLibSSL(path string) bool {
	base := filepath.Base(path)
	return strings.HasPrefix(base, "libssl.so")
}

// checkSiblingCryptoForBoringSSL checks the sibling libcrypto.so for BoringSSL
// strings. BoringSSL puts its version string in libcrypto, not libssl, so
// isBoringSSL fails when scanning libssl.so alone.
func checkSiblingCryptoForBoringSSL(libsslPath string) (string, TLSOffsets, error) {
	dir := filepath.Dir(libsslPath)
	// Try common libcrypto names in the same directory.
	for _, name := range []string{"libcrypto.so", "libcrypto.so.3", "libcrypto.so.1.1"} {
		cryptoPath := filepath.Join(dir, name)
		cf, err := elf.Open(cryptoPath)
		if err != nil {
			continue
		}
		boring := isBoringSSL(cf)
		_ = cf.Close()
		if boring {
			offsets, ok := tlsOffsetTable["boringssl"]
			if !ok {
				return "boringssl", TLSOffsets{}, fmt.Errorf("BoringSSL offsets not in table")
			}
			return "boringssl", offsets, nil
		}
	}
	return "", TLSOffsets{}, fmt.Errorf("no BoringSSL sibling libcrypto found")
}

func containsBytes(data, pattern []byte) bool {
	for i := 0; i+len(pattern) <= len(data); i++ {
		if startsWith(data[i:], pattern) {
			return true
		}
	}
	return false
}

// readOpenSSLVersion attempts to find the OpenSSL version string in the
// library's .rodata section. Looks for patterns like "OpenSSL 3.2.1 ".
func readOpenSSLVersion(f *elf.File) (string, error) {
	for _, name := range []string{".rodata", ".data"} {
		sec := f.Section(name)
		if sec == nil {
			continue
		}
		data, err := sec.Data()
		if err != nil {
			continue
		}
		if v := findVersionInData(data); v != "" {
			return v, nil
		}
	}

	// Fallback: check for OpenSSL_version_num symbol
	syms, err := f.DynamicSymbols()
	if err == nil {
		for _, sym := range syms {
			if sym.Name == "OpenSSL_version_num" && sym.Value != 0 {
				return readVersionFromSymbol(f, &sym)
			}
		}
	}

	return "", fmt.Errorf("could not determine OpenSSL version")
}

func findVersionInData(data []byte) string {
	prefix := []byte("OpenSSL ")
	for i := 0; i+len(prefix)+5 < len(data); i++ {
		if data[i] != 'O' {
			continue
		}
		if !startsWith(data[i:], prefix) {
			continue
		}
		start := i + len(prefix)
		end := start
		for end < len(data) && end-start < 20 && data[end] != ' ' && data[end] != 0 && data[end] != '\n' {
			end++
		}
		version := string(data[start:end])
		if len(version) >= 3 && version[0] >= '0' && version[0] <= '9' {
			return version
		}
	}
	return ""
}

func startsWith(data, prefix []byte) bool {
	if len(data) < len(prefix) {
		return false
	}
	for i := range prefix {
		if data[i] != prefix[i] {
			return false
		}
	}
	return true
}

func readVersionFromSymbol(f *elf.File, sym *elf.Symbol) (string, error) {
	for _, sec := range f.Sections {
		if sec.Addr > sym.Value || sym.Value >= sec.Addr+sec.Size {
			continue
		}
		offset := sym.Value - sec.Addr
		data, err := sec.Data()
		if err != nil || offset+4 > uint64(len(data)) {
			continue
		}
		var num uint32
		if f.ByteOrder == binary.LittleEndian {
			num = binary.LittleEndian.Uint32(data[offset:])
		} else {
			num = binary.BigEndian.Uint32(data[offset:])
		}
		if num > 0 {
			major := (num >> 28) & 0xF
			minor := (num >> 20) & 0xFF
			patch := (num >> 4) & 0xFF
			return fmt.Sprintf("%d.%d.%d", major, minor, patch), nil
		}
	}
	return "", fmt.Errorf("could not read version from symbol")
}

func extractMajorMinor(version string) string {
	parts := strings.SplitN(version, ".", 3)
	if len(parts) >= 2 {
		return parts[0] + "." + parts[1]
	}
	return version
}
