// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsuprobeScratchBuf struct {
	_            structs.HostLayout
	UserDataPtr  uint64
	ReadLen      uint32
	HostOffset   uint32
	HostValueLen uint32
	HostValue    [32]int8
	Data         [256]int8
	_            [4]byte
}

type tlsuprobeSecretKey struct {
	_      structs.HostLayout
	Prefix [16]int8
}

type tlsuprobeSecretValue struct {
	_           structs.HostLayout
	Len         uint32
	RealSecret  [128]int8
	HostLen     uint32
	AllowedHost [32]int8
}

// loadTlsuprobe returns the embedded CollectionSpec for tlsuprobe.
func loadTlsuprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsuprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tlsuprobe: %w", err)
	}

	return spec, err
}

// loadTlsuprobeObjects loads tlsuprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsuprobeObjects
//	*tlsuprobePrograms
//	*tlsuprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsuprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTlsuprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsuprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsuprobeSpecs struct {
	tlsuprobeProgramSpecs
	tlsuprobeMapSpecs
	tlsuprobeVariableSpecs
}

// tlsuprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsuprobeProgramSpecs struct {
	BpfPhase2Rewrite    *ebpf.ProgramSpec `ebpf:"bpf_phase2_rewrite"`
	BpfUprobeGoTlsWrite *ebpf.ProgramSpec `ebpf:"bpf_uprobe_go_tls_write"`
	BpfUprobeSslWrite   *ebpf.ProgramSpec `ebpf:"bpf_uprobe_ssl_write"`
}

// tlsuprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsuprobeMapSpecs struct {
	ProgArray *ebpf.MapSpec `ebpf:"prog_array"`
	Scratch   *ebpf.MapSpec `ebpf:"scratch"`
	SecretMap *ebpf.MapSpec `ebpf:"secret_map"`
	TlsEvents *ebpf.MapSpec `ebpf:"tls_events"`
}

// tlsuprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsuprobeVariableSpecs struct {
}

// tlsuprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsuprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsuprobeObjects struct {
	tlsuprobePrograms
	tlsuprobeMaps
	tlsuprobeVariables
}

func (o *tlsuprobeObjects) Close() error {
	return _TlsuprobeClose(
		&o.tlsuprobePrograms,
		&o.tlsuprobeMaps,
	)
}

// tlsuprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsuprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsuprobeMaps struct {
	ProgArray *ebpf.Map `ebpf:"prog_array"`
	Scratch   *ebpf.Map `ebpf:"scratch"`
	SecretMap *ebpf.Map `ebpf:"secret_map"`
	TlsEvents *ebpf.Map `ebpf:"tls_events"`
}

func (m *tlsuprobeMaps) Close() error {
	return _TlsuprobeClose(
		m.ProgArray,
		m.Scratch,
		m.SecretMap,
		m.TlsEvents,
	)
}

// tlsuprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsuprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsuprobeVariables struct {
}

// tlsuprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsuprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsuprobePrograms struct {
	BpfPhase2Rewrite    *ebpf.Program `ebpf:"bpf_phase2_rewrite"`
	BpfUprobeGoTlsWrite *ebpf.Program `ebpf:"bpf_uprobe_go_tls_write"`
	BpfUprobeSslWrite   *ebpf.Program `ebpf:"bpf_uprobe_ssl_write"`
}

func (p *tlsuprobePrograms) Close() error {
	return _TlsuprobeClose(
		p.BpfPhase2Rewrite,
		p.BpfUprobeGoTlsWrite,
		p.BpfUprobeSslWrite,
	)
}

func _TlsuprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlsuprobe_bpfel.o
var _TlsuprobeBytes []byte
